apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: vgjs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vgjs
    app.kubernetes.io/part-of: byoc-app-qnlu
  name: vgjscyhy
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: vgjs
    weight: null
status: {}
